# Generated by Django 5.2.1 on 2025-05-31 18:27

from django.db import migrations

def populate_status(apps, schema_editor):
    entries = {
        "Draft": "A post that is still being written and is not yet ready for publication.",
        "Published": "A post that has been completed and is visible to the public.",
        "Archived": "A post that is no longer actively maintained but is kept for reference."
    }
    Status = apps.get_model('posts', 'Status')
    for key, value in entries.items():
        Status.obj = Status(name=key, description=value)
        Status.obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
